#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

#include "symbol_table.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

extern int yylineno;
extern FILE *yyin;
extern char *yytext;

void yyerror(const char* s);
int yylex(void);

// TAC structure
typedef struct {
    char* result;
    char* op;
    char* arg1;
    char* arg2;
} TAC;

TAC tac_list[10000];
int tac_count = 0;
int temp_count = 0;
int label_count = 0;
char* current_function = NULL;

char* new_temp() {
    char* temp = malloc(10);
    sprintf(temp, "t%d", temp_count++);
    return temp;
}

char* new_label() {
    char* label = malloc(10);
    sprintf(label, "L%d", label_count++);
    return label;
}

void emit_tac(char* result, char* op, char* arg1, char* arg2) {
    tac_list[tac_count].result = result ? strdup(result) : NULL;
    tac_list[tac_count].op = op ? strdup(op) : NULL;
    tac_list[tac_count].arg1 = arg1 ? strdup(arg1) : NULL;
    tac_list[tac_count].arg2 = arg2 ? strdup(arg2) : NULL;
    tac_count++;
}

void print_tac() {
    printf("\nThree-Address Code:\n");
    for (int i = 0; i < tac_count; i++) {
        TAC *t = &tac_list[i];
        if (t->op && strcmp(t->op, "func") == 0) {
            printf("func %s\n", t->arg1 ? t->arg1 : "");
        } else if (t->op && strcmp(t->op, "endfunc") == 0) {
            printf("endfunc %s\n", t->arg1 ? t->arg1 : "");
        } else if (t->op && strcmp(t->op, "label") == 0) {
            printf("%s: label\n", t->result ? t->result : "");
        } else if (t->op && strcmp(t->op, "goto") == 0) {
            printf("goto %s\n", t->arg1 ? t->arg1 : "");
        } else if (t->op && strcmp(t->op, "ifz") == 0) {
            printf("ifz %s %s\n", t->arg1 ? t->arg1 : "", t->arg2 ? t->arg2 : "");
        } else if (t->op && strcmp(t->op, "printf") == 0) {
            printf("printf %s%s%s\n", t->arg1 ? t->arg1 : "",
                   t->arg2 ? " " : "", t->arg2 ? t->arg2 : "");
        } else if (t->op && strcmp(t->op, "scanf") == 0) {
            printf("%s = scanf %s\n", t->result ? t->result : "", t->arg1 ? t->arg1 : "");
        } else if (t->op && strcmp(t->op, "return") == 0) {
            printf("return %s\n", t->arg1 ? t->arg1 : "");
        } else if (t->op && strcmp(t->op, "declare") == 0) {
            printf("%s: declare %s\n", t->result ? t->result : "", t->arg1 ? t->arg1 : "");
        } else if (t->result) {
            printf("%s = %s %s %s\n", t->result ? t->result : "",
                   t->arg1 ? t->arg1 : "", t->op ? t->op : "",
                   t->arg2 ? t->arg2 : "");
        } else {
            printf("%s %s %s\n", t->arg1 ? t->arg1 : "",
                   t->op ? t->op : "", t->arg2 ? t->arg2 : "");
        }
    }
}

void print_tac_to_file(const char *filename) {
    FILE *file = fopen(filename, "w");
    if (!file) {
        perror("Failed to open file");
        return;
    }

    fprintf(file, "Three-Address Code:\n");
    for (int i = 0; i < tac_count; i++) {
        TAC *t = &tac_list[i];
        if (t->op && strcmp(t->op, "func") == 0) {
            fprintf(file, "func %s\n", t->arg1 ? t->arg1 : "");
        } else if (t->op && strcmp(t->op, "endfunc") == 0) {
            fprintf(file, "endfunc %s\n", t->arg1 ? t->arg1 : "");
        } else if (t->op && strcmp(t->op, "label") == 0) {
            fprintf(file, "%s: label\n", t->result ? t->result : "");
        } else if (t->op && strcmp(t->op, "goto") == 0) {
            fprintf(file, "goto %s\n", t->arg1 ? t->arg1 : "");
        } else if (t->op && strcmp(t->op, "ifz") == 0) {
            fprintf(file, "ifz %s %s\n", t->arg1 ? t->arg1 : "", t->arg2 ? t->arg2 : "");
        } else if (t->op && strcmp(t->op, "printf") == 0) {
            fprintf(file, "printf %s%s%s\n", t->arg1 ? t->arg1 : "",
                    t->arg2 ? " " : "", t->arg2 ? t->arg2 : "");
        } else if (t->op && strcmp(t->op, "scanf") == 0) {
            fprintf(file, "%s = scanf %s\n", t->result ? t->result : "", t->arg1 ? t->arg1 : "");
        } else if (t->op && strcmp(t->op, "return") == 0) {
            fprintf(file, "return %s\n", t->arg1 ? t->arg1 : "");
        } else if (t->op && strcmp(t->op, "declare") == 0) {
            fprintf(file, "%s: declare %s\n", t->result ? t->result : "", t->arg1 ? t->arg1 : "");
        } else if (t->result) {
            fprintf(file, "%s = %s %s %s\n", t->result ? t->result : "",
                    t->arg1 ? t->arg1 : "", t->op ? t->op : "",
                    t->arg2 ? t->arg2 : "");
        } else {
            fprintf(file, "%s %s %s\n", t->arg1 ? t->arg1 : "",
                    t->op ? t->op : "", t->arg2 ? t->arg2 : "");
        }
    }

    fclose(file);
}


#line 126 "parser.y"
typedef union {
    int num;
    char* id;
    struct { int value; char* type; char* id; } expr;
    struct { char* type; } type_spec;
    struct { char* label1; char* label2; char* label3; } labels;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	NUMBER	258
#define	IDENTIFIER	259
#define	STRING	260
#define	FILENAME	261
#define	INT	262
#define	VOID	263
#define	MAIN	264
#define	IF	265
#define	ELSE	266
#define	WHILE	267
#define	FOR	268
#define	PRINTF	269
#define	SCANF	270
#define	RETURN	271
#define	INC	272
#define	DEC	273
#define	EQ	274
#define	ASSIGN	275
#define	NE	276
#define	LE	277
#define	GE	278
#define	LT	279
#define	GT	280
#define	PLUS	281
#define	MINUS	282
#define	MUL	283
#define	DIV	284
#define	SEMICOLON	285
#define	LPAREN	286
#define	RPAREN	287
#define	LBRACE	288
#define	RBRACE	289
#define	COMMA	290
#define	HASH	291
#define	INCLUDE	292
#define	DEFINE	293
#define	AMPERSAND	294


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int NUMBER;
static const int IDENTIFIER;
static const int STRING;
static const int FILENAME;
static const int INT;
static const int VOID;
static const int MAIN;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int FOR;
static const int PRINTF;
static const int SCANF;
static const int RETURN;
static const int INC;
static const int DEC;
static const int EQ;
static const int ASSIGN;
static const int NE;
static const int LE;
static const int GE;
static const int LT;
static const int GT;
static const int PLUS;
static const int MINUS;
static const int MUL;
static const int DIV;
static const int SEMICOLON;
static const int LPAREN;
static const int RPAREN;
static const int LBRACE;
static const int RBRACE;
static const int COMMA;
static const int HASH;
static const int INCLUDE;
static const int DEFINE;
static const int AMPERSAND;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,NUMBER=258
	,IDENTIFIER=259
	,STRING=260
	,FILENAME=261
	,INT=262
	,VOID=263
	,MAIN=264
	,IF=265
	,ELSE=266
	,WHILE=267
	,FOR=268
	,PRINTF=269
	,SCANF=270
	,RETURN=271
	,INC=272
	,DEC=273
	,EQ=274
	,ASSIGN=275
	,NE=276
	,LE=277
	,GE=278
	,LT=279
	,GT=280
	,PLUS=281
	,MINUS=282
	,MUL=283
	,DIV=284
	,SEMICOLON=285
	,LPAREN=286
	,RPAREN=287
	,LBRACE=288
	,RBRACE=289
	,COMMA=290
	,HASH=291
	,INCLUDE=292
	,DEFINE=293
	,AMPERSAND=294


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::NUMBER=258;
const int YY_parse_CLASS::IDENTIFIER=259;
const int YY_parse_CLASS::STRING=260;
const int YY_parse_CLASS::FILENAME=261;
const int YY_parse_CLASS::INT=262;
const int YY_parse_CLASS::VOID=263;
const int YY_parse_CLASS::MAIN=264;
const int YY_parse_CLASS::IF=265;
const int YY_parse_CLASS::ELSE=266;
const int YY_parse_CLASS::WHILE=267;
const int YY_parse_CLASS::FOR=268;
const int YY_parse_CLASS::PRINTF=269;
const int YY_parse_CLASS::SCANF=270;
const int YY_parse_CLASS::RETURN=271;
const int YY_parse_CLASS::INC=272;
const int YY_parse_CLASS::DEC=273;
const int YY_parse_CLASS::EQ=274;
const int YY_parse_CLASS::ASSIGN=275;
const int YY_parse_CLASS::NE=276;
const int YY_parse_CLASS::LE=277;
const int YY_parse_CLASS::GE=278;
const int YY_parse_CLASS::LT=279;
const int YY_parse_CLASS::GT=280;
const int YY_parse_CLASS::PLUS=281;
const int YY_parse_CLASS::MINUS=282;
const int YY_parse_CLASS::MUL=283;
const int YY_parse_CLASS::DIV=284;
const int YY_parse_CLASS::SEMICOLON=285;
const int YY_parse_CLASS::LPAREN=286;
const int YY_parse_CLASS::RPAREN=287;
const int YY_parse_CLASS::LBRACE=288;
const int YY_parse_CLASS::RBRACE=289;
const int YY_parse_CLASS::COMMA=290;
const int YY_parse_CLASS::HASH=291;
const int YY_parse_CLASS::INCLUDE=292;
const int YY_parse_CLASS::DEFINE=293;
const int YY_parse_CLASS::AMPERSAND=294;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		151
#define	YYFLAG		-32768
#define	YYNTBASE	40

#define YYTRANSLATE(x) ((unsigned)(x) <= 294 ? yytranslate[x] : 70)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,    12,    14,    15,    18,    20,    26,    30,    33,
    34,    36,    38,    45,    51,    53,    55,    57,    61,    64,
    65,    75,    76,    85,    88,    89,    91,    94,    97,   100,
   103,   105,   107,   110,   112,   115,   116,   121,   123,   129,
   137,   140,   144,   148,   152,   156,   160,   164,   168,   172,
   176,   180,   184,   188,   190,   192,   194,   199,   206,   214,
   220,   230,   233,   236,   240,   245,   249,   251
};

static const short yyrhs[] = {    -1,
    42,    45,     7,     9,    31,    32,    33,    41,    54,    34,
     0,    43,     0,     0,    43,    44,     0,    44,     0,    36,
    37,    24,     6,    25,     0,    36,    38,     4,     0,    45,
    46,     0,     0,    47,     0,    51,     0,    48,     4,    31,
    49,    32,    30,     0,    48,     4,    31,    32,    30,     0,
     7,     0,     8,     0,    50,     0,    49,    35,    50,     0,
    48,     4,     0,     0,    48,     4,    31,    49,    32,    33,
    52,    54,    34,     0,     0,    48,     4,    31,    32,    33,
    53,    54,    34,     0,    54,    55,     0,     0,    56,     0,
    59,    30,     0,    60,    30,     0,    62,    30,     0,    63,
    30,     0,    64,     0,    65,     0,    66,    30,     0,    67,
     0,    68,    30,     0,     0,    33,    57,    54,    34,     0,
    58,     0,    10,    31,    61,    32,    55,     0,    10,    31,
    61,    32,    55,    11,    55,     0,     7,     4,     0,     4,
    20,    61,     0,    61,    26,    61,     0,    61,    27,    61,
     0,    61,    28,    61,     0,    61,    29,    61,     0,    61,
    19,    61,     0,    61,    21,    61,     0,    61,    24,    61,
     0,    61,    25,    61,     0,    61,    22,    61,     0,    61,
    23,    61,     0,    31,    61,    32,     0,     3,     0,     4,
     0,    68,     0,    14,    31,     5,    32,     0,    14,    31,
     5,    35,     4,    32,     0,    15,    31,     5,    35,    39,
     4,    32,     0,    12,    31,    61,    32,    55,     0,    13,
    31,    60,    30,    61,    30,    66,    32,    55,     0,     4,
    17,     0,     4,    18,     0,    16,    61,    30,     0,     4,
    31,    69,    32,     0,     4,    31,    32,     0,    61,     0,
    69,    35,    61,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   160,   176,   189,   191,   194,   196,   199,   205,   212,   214,
   217,   219,   222,   237,   253,   255,   258,   260,   263,   275,
   290,   300,   314,   326,   333,   341,   350,   357,   363,   369,
   375,   381,   387,   393,   399,   405,   409,   416,   424,   436,
   452,   467,   482,   498,   513,   528,   543,   558,   573,   588,
   603,   618,   633,   639,   649,   663,   671,   678,   691,   705,
   722,   742,   755,   769,   786,   801,   817,   824
};

static const char * const yytname[] = {   "$","error","$illegal.","NUMBER","IDENTIFIER",
"STRING","FILENAME","INT","VOID","MAIN","IF","ELSE","WHILE","FOR","PRINTF","SCANF",
"RETURN","INC","DEC","EQ","ASSIGN","NE","LE","GE","LT","GT","PLUS","MINUS","MUL",
"DIV","SEMICOLON","LPAREN","RPAREN","LBRACE","RBRACE","COMMA","HASH","INCLUDE",
"DEFINE","AMPERSAND","program","@1","preprocessor_directives_opt","preprocessor_directives",
"preprocessor_directive","declarations","declaration_item","function_prototype",
"type_specifier","parameter_list","parameter","function_definition","@2","@3",
"statements","statement","matched_stmt","@4","if_stmt","declaration","assignment",
"expression","print_stmt","input_stmt","while_stmt","for_stmt","increment","return_stmt",
"function_call","argument_list",""
};
#endif

static const short yyr1[] = {     0,
    41,    40,    42,    42,    43,    43,    44,    44,    45,    45,
    46,    46,    47,    47,    48,    48,    49,    49,    50,    52,
    51,    53,    51,    54,    54,    55,    56,    56,    56,    56,
    56,    56,    56,    56,    56,    57,    56,    56,    58,    58,
    59,    60,    61,    61,    61,    61,    61,    61,    61,    61,
    61,    61,    61,    61,    61,    61,    62,    62,    63,    64,
    65,    66,    66,    67,    68,    68,    69,    69
};

static const short yyr2[] = {     0,
     0,    10,     1,     0,     2,     1,     5,     3,     2,     0,
     1,     1,     6,     5,     1,     1,     1,     3,     2,     0,
     9,     0,     8,     2,     0,     1,     2,     2,     2,     2,
     1,     1,     2,     1,     2,     0,     4,     1,     5,     7,
     2,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     1,     1,     1,     4,     6,     7,     5,
     9,     2,     2,     3,     4,     3,     1,     3
};

static const short yydefact[] = {     4,
     0,    10,     3,     6,     0,     0,     0,     5,     0,     8,
    15,    16,     9,    11,     0,    12,     0,     0,     0,     7,
     0,     0,     0,    15,     0,     0,     0,    17,     1,    14,
    22,    19,     0,     0,    25,    25,    13,    20,    18,     0,
     0,    25,     0,     0,     0,     0,     0,     0,     0,     0,
    36,     2,    24,    26,    38,     0,     0,     0,     0,    31,
    32,     0,    34,     0,    23,     0,    62,    63,     0,     0,
    41,     0,     0,     0,     0,     0,    54,    55,     0,     0,
    56,    25,    27,    28,    29,    30,    33,    35,    21,    42,
    66,    67,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    64,     0,    65,     0,     0,     0,     0,    57,     0,     0,
    53,    47,    48,    51,    52,    49,    50,    43,    44,    45,
    46,    37,    68,    39,    60,     0,     0,     0,     0,     0,
    58,     0,    40,     0,     0,    59,     0,    61,     0,     0,
     0
};

static const short yydefgoto[] = {   149,
    35,     2,     3,     4,     7,    13,    14,    26,    27,    28,
    16,    42,    36,    40,    53,    54,    82,    55,    56,    57,
    80,    58,    59,    60,    61,    62,    63,    81,    93
};

static const short yypact[] = {   -32,
   -22,-32768,   -32,-32768,   -14,    28,    16,-32768,    72,-32768,
    49,-32768,-32768,-32768,    82,-32768,    80,    87,    93,-32768,
    74,     1,    78,-32768,   -19,   115,    32,-32768,-32768,-32768,
-32768,-32768,    35,    86,-32768,-32768,-32768,-32768,-32768,    15,
    47,-32768,    53,   127,   110,   125,   137,   151,   163,    52,
-32768,-32768,-32768,-32768,-32768,   112,   114,   175,   181,-32768,
-32768,   182,-32768,   186,-32768,    75,-32768,-32768,    52,    14,
-32768,    52,    52,   218,   219,   220,-32768,   192,    52,   150,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   174,
-32768,   174,    34,   111,   126,   206,   197,    42,   193,   138,
    52,    52,    52,    52,    52,    52,    52,    52,    52,    52,
-32768,    88,-32768,    52,   113,   113,    52,-32768,   225,   191,
-32768,    91,    91,    91,    91,    91,    91,   185,   185,   196,
   196,-32768,   174,   221,-32768,   162,   199,   229,   113,   230,
-32768,   203,-32768,    79,   204,-32768,   113,-32768,   237,   238,
-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,-32768,   236,-32768,-32768,-32768,   233,-32768,   207,
-32768,-32768,-32768,   -29,   -95,-32768,-32768,-32768,-32768,   168,
   -67,-32768,-32768,-32768,-32768,   103,-32768,   -40,-32768
};


#define	YYLAST		243


static const short yytable[] = {    64,
    64,    90,    92,     1,    94,    95,    41,    24,    12,     9,
    30,   100,    66,    31,     5,     6,    77,    78,    43,   134,
   135,    44,    11,    12,    45,    64,    46,    47,    48,    49,
    50,    10,    25,   122,   123,   124,   125,   126,   127,   128,
   129,   130,   131,   143,    79,    91,   133,    51,    52,   136,
    43,   148,   112,    44,    77,    78,    45,    18,    46,    47,
    48,    49,    50,    33,    37,   113,    34,    38,   114,    67,
    68,    64,    69,   118,    64,    64,   119,    17,    43,    51,
    65,    44,    79,    70,    45,    19,    46,    47,    48,    49,
    50,    43,    24,    12,    44,    67,    68,    45,    64,    46,
    47,    48,    49,    50,    20,    23,    64,    51,    89,-32768,
    29,-32768,-32768,-32768,-32768,-32768,    43,    21,    32,    44,
    51,   132,    45,    22,    46,    47,    48,    49,    50,   101,
    71,   102,   103,   104,   105,   106,   107,   108,   109,   110,
    72,    83,   115,    84,   101,    51,   102,   103,   104,   105,
   106,   107,   108,   109,   110,    73,   101,   116,   102,   103,
   104,   105,   106,   107,   108,   109,   110,    74,   101,   121,
   102,   103,   104,   105,   106,   107,   108,   109,   110,   111,
   101,    75,   102,   103,   104,   105,   106,   107,   108,   109,
   110,   140,   101,    76,   102,   103,   104,   105,   106,   107,
   108,   109,   110,   101,    85,   102,   103,   104,   105,   106,
    86,    87,   109,   110,   101,    88,   102,   103,   104,   105,
   106,    96,    70,    98,    99,    69,   117,   120,   137,   138,
   141,   139,   142,   144,   146,   147,   150,   151,     8,    15,
    39,    97,   145
};

static const short yycheck[] = {    40,
    41,    69,    70,    36,    72,    73,    36,     7,     8,    24,
    30,    79,    42,    33,    37,    38,     3,     4,     4,   115,
   116,     7,     7,     8,    10,    66,    12,    13,    14,    15,
    16,     4,    32,   101,   102,   103,   104,   105,   106,   107,
   108,   109,   110,   139,    31,    32,   114,    33,    34,   117,
     4,   147,    82,     7,     3,     4,    10,     9,    12,    13,
    14,    15,    16,    32,    30,    32,    35,    33,    35,    17,
    18,   112,    20,    32,   115,   116,    35,     6,     4,    33,
    34,     7,    31,    31,    10,     4,    12,    13,    14,    15,
    16,     4,     7,     8,     7,    17,    18,    10,   139,    12,
    13,    14,    15,    16,    25,    32,   147,    33,    34,    19,
    33,    21,    22,    23,    24,    25,     4,    31,     4,     7,
    33,    34,    10,    31,    12,    13,    14,    15,    16,    19,
     4,    21,    22,    23,    24,    25,    26,    27,    28,    29,
    31,    30,    32,    30,    19,    33,    21,    22,    23,    24,
    25,    26,    27,    28,    29,    31,    19,    32,    21,    22,
    23,    24,    25,    26,    27,    28,    29,    31,    19,    32,
    21,    22,    23,    24,    25,    26,    27,    28,    29,    30,
    19,    31,    21,    22,    23,    24,    25,    26,    27,    28,
    29,    30,    19,    31,    21,    22,    23,    24,    25,    26,
    27,    28,    29,    19,    30,    21,    22,    23,    24,    25,
    30,    30,    28,    29,    19,    30,    21,    22,    23,    24,
    25,     4,    31,     5,     5,    20,    30,    35,     4,    39,
    32,    11,     4,     4,    32,    32,     0,     0,     3,     7,
    34,    74,   140
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 163 "parser.y"
{
        if (symbol_exists("main")) {
            yyerror("Redeclaration of main");
        } else {
            insert_symbol("main", "function");
            Symbol* func = lookup_symbol("main");
            func->declared = 1;
            func->type = strdup("int");
            current_function = strdup("main");
            emit_tac(NULL, "func", "main", NULL);
        }
        push_scope();
    ;
    break;}
case 2:
#line 177 "parser.y"
{
        emit_tac(NULL, "endfunc", "main", NULL);
        pop_scope();
        free(current_function);
        current_function = NULL;
        printf("✅ Program parsed successfully!\n");
        print_symbol_table();
        print_tac();
        print_tac_to_file("tac_output.txt");
    ;
    break;}
case 7:
#line 201 "parser.y"
{
        printf("✅ Include directive: <%s>\n", yyvsp[-1].id);
        free(yyvsp[-1].id);
    ;
    break;}
case 8:
#line 206 "parser.y"
{
        printf("✅ Define directive: %s\n", yyvsp[0].id);
        free(yyvsp[0].id);
    ;
    break;}
case 13:
#line 224 "parser.y"
{
        if (symbol_exists(yyvsp[-4].id)) {
            yyerror("Redeclaration of function");
        } else {
            insert_symbol(yyvsp[-4].id, "function");
            Symbol* func = lookup_symbol(yyvsp[-4].id);
            func->declared = 1;
            func->type = strdup(yyvsp[-5].type_spec.type);
            printf("✅ Function prototype declared: %s\n", yyvsp[-4].id);
        }
        free(yyvsp[-4].id);
        free(yyvsp[-5].type_spec.type);
    ;
    break;}
case 14:
#line 238 "parser.y"
{
        if (symbol_exists(yyvsp[-3].id)) {
            yyerror("Redeclaration of function");
        } else {
            insert_symbol(yyvsp[-3].id, "function");
            Symbol* func = lookup_symbol(yyvsp[-3].id);
            func->declared = 1;
            func->type = strdup(yyvsp[-4].type_spec.type);
            printf("✅ Function prototype declared: %s\n", yyvsp[-3].id);
        }
        free(yyvsp[-3].id);
        free(yyvsp[-4].type_spec.type);
    ;
    break;}
case 15:
#line 254 "parser.y"
{ yyval.type_spec.type = strdup("int"); ;
    break;}
case 16:
#line 255 "parser.y"
{ yyval.type_spec.type = strdup("void"); ;
    break;}
case 19:
#line 265 "parser.y"
{
        Symbol* func = symbol_table;
        add_parameter(func, yyvsp[0].id, yyvsp[-1].type_spec.type);
        insert_symbol(yyvsp[0].id, yyvsp[-1].type_spec.type);
        declare_symbol(yyvsp[0].id);
        free(yyvsp[-1].type_spec.type);
        free(yyvsp[0].id);
    ;
    break;}
case 20:
#line 277 "parser.y"
{
        if (symbol_exists(yyvsp[-4].id)) {
            yyerror("Redeclaration of function");
        } else {
            insert_symbol(yyvsp[-4].id, "function");
            Symbol* func = lookup_symbol(yyvsp[-4].id);
            func->declared = 1;
            func->type = strdup(yyvsp[-5].type_spec.type);
            current_function = strdup(yyvsp[-4].id);
            emit_tac(NULL, "func", yyvsp[-4].id, NULL);
        }
        push_scope();
    ;
    break;}
case 21:
#line 291 "parser.y"
{
        emit_tac(NULL, "endfunc", yyvsp[-7].id, NULL);
        printf("✅ Function defined: %s\n", yyvsp[-7].id);
        pop_scope();
        free(current_function);
        current_function = NULL;
        free(yyvsp[-7].id);
        free(yyvsp[-8].type_spec.type);
    ;
    break;}
case 22:
#line 301 "parser.y"
{
        if (symbol_exists(yyvsp[-3].id)) {
            yyerror("Redeclaration of function");
        } else {
            insert_symbol(yyvsp[-3].id, "function");
            Symbol* func = lookup_symbol(yyvsp[-3].id);
            func->declared = 1;
            func->type = strdup(yyvsp[-4].type_spec.type);
            current_function = strdup(yyvsp[-3].id);
            emit_tac(NULL, "func", yyvsp[-3].id, NULL);
        }
        push_scope();
    ;
    break;}
case 23:
#line 315 "parser.y"
{
        emit_tac(NULL, "endfunc", yyvsp[-6].id, NULL);
        printf("✅ Function defined: %s\n", yyvsp[-6].id);
        pop_scope();
        free(current_function);
        current_function = NULL;
        free(yyvsp[-6].id);
        free(yyvsp[-7].type_spec.type);
    ;
    break;}
case 24:
#line 328 "parser.y"
{
        yyval.labels.label1 = NULL;
        yyval.labels.label2 = NULL;
        yyval.labels.label3 = NULL;
    ;
    break;}
case 25:
#line 334 "parser.y"
{
        yyval.labels.label1 = NULL;
        yyval.labels.label2 = NULL;
        yyval.labels.label3 = NULL;
    ;
    break;}
case 26:
#line 343 "parser.y"
{
        yyval.labels.label1 = yyvsp[0].labels.label1;
        yyval.labels.label2 = yyvsp[0].labels.label2;
        yyval.labels.label3 = yyvsp[0].labels.label3;
    ;
    break;}
case 27:
#line 352 "parser.y"
{
        yyval.labels.label1 = NULL;
        yyval.labels.label2 = NULL;
        yyval.labels.label3 = NULL;
    ;
    break;}
case 28:
#line 358 "parser.y"
{
        yyval.labels.label1 = NULL;
        yyval.labels.label2 = NULL;
        yyval.labels.label3 = NULL;
    ;
    break;}
case 29:
#line 364 "parser.y"
{
        yyval.labels.label1 = NULL;
        yyval.labels.label2 = NULL;
        yyval.labels.label3 = NULL;
    ;
    break;}
case 30:
#line 370 "parser.y"
{
        yyval.labels.label1 = NULL;
        yyval.labels.label2 = NULL;
        yyval.labels.label3 = NULL;
    ;
    break;}
case 31:
#line 376 "parser.y"
{
        yyval.labels.label1 = yyvsp[0].labels.label1;
        yyval.labels.label2 = yyvsp[0].labels.label2;
        yyval.labels.label3 = yyvsp[0].labels.label3;
    ;
    break;}
case 32:
#line 382 "parser.y"
{
        yyval.labels.label1 = yyvsp[0].labels.label1;
        yyval.labels.label2 = yyvsp[0].labels.label2;
        yyval.labels.label3 = yyvsp[0].labels.label3;
    ;
    break;}
case 33:
#line 388 "parser.y"
{
        yyval.labels.label1 = NULL;
        yyval.labels.label2 = NULL;
        yyval.labels.label3 = NULL;
    ;
    break;}
case 34:
#line 394 "parser.y"
{
        yyval.labels.label1 = NULL;
        yyval.labels.label2 = NULL;
        yyval.labels.label3 = NULL;
    ;
    break;}
case 35:
#line 400 "parser.y"
{
        yyval.labels.label1 = NULL;
        yyval.labels.label2 = NULL;
        yyval.labels.label3 = NULL;
    ;
    break;}
case 36:
#line 406 "parser.y"
{
        push_scope();
    ;
    break;}
case 37:
#line 410 "parser.y"
{
        pop_scope();
        yyval.labels.label1 = NULL;
        yyval.labels.label2 = NULL;
        yyval.labels.label3 = NULL;
    ;
    break;}
case 38:
#line 417 "parser.y"
{
        yyval.labels.label1 = yyvsp[0].labels.label1;
        yyval.labels.label2 = yyvsp[0].labels.label2;
        yyval.labels.label3 = yyvsp[0].labels.label3;
    ;
    break;}
case 39:
#line 426 "parser.y"
{
        char* label1 = new_label();
        emit_tac(NULL, "ifz", yyvsp[-2].expr.id, label1);
        emit_tac(label1, "label", NULL, NULL);
        yyval.labels.label1 = label1;
        yyval.labels.label2 = NULL;
        yyval.labels.label3 = NULL;
        free(yyvsp[-2].expr.type);
        free(yyvsp[-2].expr.id);
    ;
    break;}
case 40:
#line 437 "parser.y"
{
        char* label1 = new_label();
        char* label2 = new_label();
        emit_tac(NULL, "ifz", yyvsp[-4].expr.id, label1);
        emit_tac(NULL, "goto", label2, NULL);
        emit_tac(label1, "label", NULL, NULL);
        emit_tac(label2, "label", NULL, NULL);
        yyval.labels.label1 = label1;
        yyval.labels.label2 = label2;
        yyval.labels.label3 = NULL;
        free(yyvsp[-4].expr.type);
        free(yyvsp[-4].expr.id);
    ;
    break;}
case 41:
#line 454 "parser.y"
{
        if (symbol_exists(yyvsp[0].id)) {
            yyerror("Redeclaration of variable");
        } else {
            insert_symbol(yyvsp[0].id, "int");
            declare_symbol(yyvsp[0].id);
            printf("✅ Declaration: %s of type int\n", yyvsp[0].id);
            emit_tac(yyvsp[0].id, "declare", "int", NULL);
        }
        free(yyvsp[0].id);
    ;
    break;}
case 42:
#line 469 "parser.y"
{
        if (!symbol_exists(yyvsp[-2].id)) {
            yyerror("Assignment to undeclared variable");
        } else {
            emit_tac(yyvsp[-2].id, "=", yyvsp[0].expr.id, NULL);
            printf("✅ Assignment: %s = (expression)\n", yyvsp[-2].id);
        }
        free(yyvsp[-2].id);
        free(yyvsp[0].expr.type);
        free(yyvsp[0].expr.id);
    ;
    break;}
case 43:
#line 484 "parser.y"
{
        if (strcmp(yyvsp[-2].expr.type, "int") != 0 || strcmp(yyvsp[0].expr.type, "int") != 0) {
            yyerror("Type mismatch in addition");
        }
        char* temp = new_temp();
        emit_tac(temp, "+", yyvsp[-2].expr.id, yyvsp[0].expr.id);
        yyval.expr.type = strdup("int");
        yyval.expr.id = temp;
        yyval.expr.value = 0;
        free(yyvsp[-2].expr.type);
        free(yyvsp[0].expr.type);
        free(yyvsp[-2].expr.id);
        free(yyvsp[0].expr.id);
    ;
    break;}
case 44:
#line 499 "parser.y"
{
        if (strcmp(yyvsp[-2].expr.type, "int") != 0 || strcmp(yyvsp[0].expr.type, "int") != 0) {
            yyerror("Type mismatch in subtraction");
        }
        char* temp = new_temp();
        emit_tac(temp, "-", yyvsp[-2].expr.id, yyvsp[0].expr.id);
        yyval.expr.type = strdup("int");
        yyval.expr.id = temp;
        yyval.expr.value = 0;
        free(yyvsp[-2].expr.type);
        free(yyvsp[0].expr.type);
        free(yyvsp[-2].expr.id);
        free(yyvsp[0].expr.id);
    ;
    break;}
case 45:
#line 514 "parser.y"
{
        if (strcmp(yyvsp[-2].expr.type, "int") != 0 || strcmp(yyvsp[0].expr.type, "int") != 0) {
            yyerror("Type mismatch in multiplication");
        }
        char* temp = new_temp();
        emit_tac(temp, "*", yyvsp[-2].expr.id, yyvsp[0].expr.id);
        yyval.expr.type = strdup("int");
        yyval.expr.id = temp;
        yyval.expr.value = 0;
        free(yyvsp[-2].expr.type);
        free(yyvsp[0].expr.type);
        free(yyvsp[-2].expr.id);
        free(yyvsp[0].expr.id);
    ;
    break;}
case 46:
#line 529 "parser.y"
{
        if (strcmp(yyvsp[-2].expr.type, "int") != 0 || strcmp(yyvsp[0].expr.type, "int") != 0) {
            yyerror("Type mismatch in division");
        }
        char* temp = new_temp();
        emit_tac(temp, "/", yyvsp[-2].expr.id, yyvsp[0].expr.id);
        yyval.expr.type = strdup("int");
        yyval.expr.id = temp;
        yyval.expr.value = 0;
        free(yyvsp[-2].expr.type);
        free(yyvsp[0].expr.type);
        free(yyvsp[-2].expr.id);
        free(yyvsp[0].expr.id);
    ;
    break;}
case 47:
#line 544 "parser.y"
{
        if (strcmp(yyvsp[-2].expr.type, "int") != 0 || strcmp(yyvsp[0].expr.type, "int") != 0) {
            yyerror("Type mismatch in equality");
        }
        char* temp = new_temp();
        emit_tac(temp, "==", yyvsp[-2].expr.id, yyvsp[0].expr.id);
        yyval.expr.type = strdup("int");
        yyval.expr.id = temp;
        yyval.expr.value = 0;
        free(yyvsp[-2].expr.type);
        free(yyvsp[0].expr.type);
        free(yyvsp[-2].expr.id);
        free(yyvsp[0].expr.id);
    ;
    break;}
case 48:
#line 559 "parser.y"
{
        if (strcmp(yyvsp[-2].expr.type, "int") != 0 || strcmp(yyvsp[0].expr.type, "int") != 0) {
            yyerror("Type mismatch in inequality");
        }
        char* temp = new_temp();
        emit_tac(temp, "!=", yyvsp[-2].expr.id, yyvsp[0].expr.id);
        yyval.expr.type = strdup("int");
        yyval.expr.id = temp;
        yyval.expr.value = 0;
        free(yyvsp[-2].expr.type);
        free(yyvsp[0].expr.type);
        free(yyvsp[-2].expr.id);
        free(yyvsp[0].expr.id);
    ;
    break;}
case 49:
#line 574 "parser.y"
{
        if (strcmp(yyvsp[-2].expr.type, "int") != 0 || strcmp(yyvsp[0].expr.type, "int") != 0) {
            yyerror("Type mismatch in less than");
        }
        char* temp = new_temp();
        emit_tac(temp, "<", yyvsp[-2].expr.id, yyvsp[0].expr.id);
        yyval.expr.type = strdup("int");
        yyval.expr.id = temp;
        yyval.expr.value = 0;
        free(yyvsp[-2].expr.type);
        free(yyvsp[0].expr.type);
        free(yyvsp[-2].expr.id);
        free(yyvsp[0].expr.id);
    ;
    break;}
case 50:
#line 589 "parser.y"
{
        if (strcmp(yyvsp[-2].expr.type, "int") != 0 || strcmp(yyvsp[0].expr.type, "int") != 0) {
            yyerror("Type mismatch in greater than");
        }
        char* temp = new_temp();
        emit_tac(temp, ">", yyvsp[-2].expr.id, yyvsp[0].expr.id);
        yyval.expr.type = strdup("int");
        yyval.expr.id = temp;
        yyval.expr.value = 0;
        free(yyvsp[-2].expr.type);
        free(yyvsp[0].expr.type);
        free(yyvsp[-2].expr.id);
        free(yyvsp[0].expr.id);
    ;
    break;}
case 51:
#line 604 "parser.y"
{
        if (strcmp(yyvsp[-2].expr.type, "int") != 0 || strcmp(yyvsp[0].expr.type, "int") != 0) {
            yyerror("Type mismatch in less than or equal");
        }
        char* temp = new_temp();
        emit_tac(temp, "<=", yyvsp[-2].expr.id, yyvsp[0].expr.id);
        yyval.expr.type = strdup("int");
        yyval.expr.id = temp;
        yyval.expr.value = 0;
        free(yyvsp[-2].expr.type);
        free(yyvsp[0].expr.type);
        free(yyvsp[-2].expr.id);
        free(yyvsp[0].expr.id);
    ;
    break;}
case 52:
#line 619 "parser.y"
{
        if (strcmp(yyvsp[-2].expr.type, "int") != 0 || strcmp(yyvsp[0].expr.type, "int") != 0) {
            yyerror("Type mismatch in greater than or equal");
        }
        char* temp = new_temp();
        emit_tac(temp, ">=", yyvsp[-2].expr.id, yyvsp[0].expr.id);
        yyval.expr.type = strdup("int");
        yyval.expr.id = temp;
        yyval.expr.value = 0;
        free(yyvsp[-2].expr.type);
        free(yyvsp[0].expr.type);
        free(yyvsp[-2].expr.id);
        free(yyvsp[0].expr.id);
    ;
    break;}
case 53:
#line 634 "parser.y"
{
        yyval.expr.type = yyvsp[-1].expr.type;
        yyval.expr.id = yyvsp[-1].expr.id;
        yyval.expr.value = yyvsp[-1].expr.value;
    ;
    break;}
case 54:
#line 640 "parser.y"
{
        char* temp = new_temp();
        char num_str[20];
        sprintf(num_str, "%d", yyvsp[0].num);
        emit_tac(temp, "=", num_str, NULL);
        yyval.expr.type = strdup("int");
        yyval.expr.id = temp;
        yyval.expr.value = yyvsp[0].num;
    ;
    break;}
case 55:
#line 650 "parser.y"
{
        Symbol* sym = lookup_symbol(yyvsp[0].id);
        if (!sym) {
            yyerror("Undeclared variable in expression");
            yyval.expr.type = strdup("int");
            yyval.expr.id = strdup("0");
        } else {
            yyval.expr.type = strdup(sym->type);
            yyval.expr.id = strdup(yyvsp[0].id);
        }
        yyval.expr.value = 0;
        free(yyvsp[0].id);
    ;
    break;}
case 56:
#line 664 "parser.y"
{
        yyval.expr.type = strdup("int");
        yyval.expr.id = yyvsp[0].id;
        yyval.expr.value = 0;
    ;
    break;}
case 57:
#line 673 "parser.y"
{
        emit_tac(NULL, "printf", yyvsp[-1].id, NULL);
        printf("✅ Print string: %s\n", yyvsp[-1].id);
        free(yyvsp[-1].id);
    ;
    break;}
case 58:
#line 679 "parser.y"
{
        if (!symbol_exists(yyvsp[-1].id)) {
            yyerror("Undeclared variable in printf");
        } else {
            emit_tac(NULL, "printf", yyvsp[-3].id, yyvsp[-1].id);
            printf("✅ Print formatted string: %s with variable: %s\n", yyvsp[-3].id, yyvsp[-1].id);
        }
        free(yyvsp[-3].id);
        free(yyvsp[-1].id);
    ;
    break;}
case 59:
#line 693 "parser.y"
{
        if (!symbol_exists(yyvsp[-1].id)) {
            yyerror("Undeclared variable in scanf");
        } else {
            emit_tac(yyvsp[-1].id, "scanf", yyvsp[-4].id, NULL);
            printf("✅ Scanf input for variable: %s\n", yyvsp[-1].id);
        }
        free(yyvsp[-4].id);
        free(yyvsp[-1].id);
    ;
    break;}
case 60:
#line 707 "parser.y"
{
        char* label1 = new_label();
        char* label2 = new_label();
        emit_tac(label1, "label", NULL, NULL);
        emit_tac(NULL, "ifz", yyvsp[-2].expr.id, label2);
        free(yyvsp[-2].expr.type);
        free(yyvsp[-2].expr.id);
        emit_tac(NULL, "goto", label1, NULL);
        emit_tac(label2, "label", NULL, NULL);
        yyval.labels.label1 = label1;
        yyval.labels.label2 = label2;
        yyval.labels.label3 = NULL;
    ;
    break;}
case 61:
#line 724 "parser.y"
{
        char* label1 = new_label();
        char* label2 = new_label();
        char* label3 = new_label();
        emit_tac(label1, "label", NULL, NULL);
        emit_tac(NULL, "ifz", yyvsp[-4].expr.id, label2);
        free(yyvsp[-4].expr.type);
        free(yyvsp[-4].expr.id);
        emit_tac(NULL, "goto", label3, NULL);
        emit_tac(label3, "label", NULL, NULL);
        emit_tac(NULL, "goto", label1, NULL);
        emit_tac(label2, "label", NULL, NULL);
        yyval.labels.label1 = label1;
        yyval.labels.label2 = label2;
        yyval.labels.label3 = label3;
    ;
    break;}
case 62:
#line 744 "parser.y"
{
        if (!symbol_exists(yyvsp[-1].id)) {
            yyerror("Undeclared variable in increment");
        } else {
            char* temp = new_temp();
            emit_tac(temp, "+", yyvsp[-1].id, "1");
            emit_tac(yyvsp[-1].id, "=", temp, NULL);
            printf("✅ Increment: %s++\n", yyvsp[-1].id);
        }
        free(yyvsp[-1].id);
    ;
    break;}
case 63:
#line 756 "parser.y"
{
        if (!symbol_exists(yyvsp[-1].id)) {
            yyerror("Undeclared variable in decrement");
        } else {
            char* temp = new_temp();
            emit_tac(temp, "-", yyvsp[-1].id, "1");
            emit_tac(yyvsp[-1].id, "=", temp, NULL);
            printf("✅ Decrement: %s--\n", yyvsp[-1].id);
        }
        free(yyvsp[-1].id);
    ;
    break;}
case 64:
#line 771 "parser.y"
{
        if (!current_function) {
            yyerror("Return statement outside function");
        } else {
            Symbol* func = lookup_symbol(current_function);
            if (func && strcmp(yyvsp[-1].expr.type, func->type) != 0) {
                yyerror("Return type mismatch");
            }
            emit_tac(NULL, "return", yyvsp[-1].expr.id, NULL);
        }
        free(yyvsp[-1].expr.type);
        free(yyvsp[-1].expr.id);
    ;
    break;}
case 65:
#line 788 "parser.y"
{
        Symbol* func = lookup_symbol(yyvsp[-3].id);
        char* temp = new_temp();
        if (!func || strcmp(func->type, "function") != 0) {
            yyerror("Call to undeclared function");
            emit_tac(temp, "=", "0", NULL);
        } else {
            emit_tac(temp, "call", yyvsp[-3].id, NULL);
            printf("✅ Function call: %s\n", yyvsp[-3].id);
        }
        yyval.id = temp;
        free(yyvsp[-3].id);
    ;
    break;}
case 66:
#line 802 "parser.y"
{
        Symbol* func = lookup_symbol(yyvsp[-2].id);
        char* temp = new_temp();
        if (!func || strcmp(func->type, "function") != 0) {
            yyerror("Call to undeclared function");
            emit_tac(temp, "=", "0", NULL);
        } else {
            emit_tac(temp, "call", yyvsp[-2].id, NULL);
            printf("✅ Function call: %s\n", yyvsp[-2].id);
        }
        yyval.id = temp;
        free(yyvsp[-2].id);
    ;
    break;}
case 67:
#line 819 "parser.y"
{
        emit_tac(NULL, "param", yyvsp[0].expr.id, NULL);
        free(yyvsp[0].expr.type);
        free(yyvsp[0].expr.id);
    ;
    break;}
case 68:
#line 825 "parser.y"
{
        emit_tac(NULL, "param", yyvsp[0].expr.id, NULL);
        free(yyvsp[0].expr.type);
        free(yyvsp[0].expr.id);
    ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 832 "parser.y"


void yyerror(const char* s) {
    fprintf(stderr, "❌ Error: %s at line %d, near '%s'\n", s, yylineno, yytext);
}

int main(int argc, char **argv) {
    if (argc > 1) {
        yyin = fopen(argv[1], "r");
        if (!yyin) {
            perror("❌ Error opening file");
            return 1;
        }
    } else {
        fprintf(stderr, "❌ Usage: %s <source_file>\n", argv[0]);
        return 1;
    }

    yyparse();
    return 0;
}